In [6]:
import numpy as np
import numpy.matlib
import random
from src.lib.xeuclidean import XEuclidean

random.seed(1337)

In [7]:
def keygen(n, p):
    # Generating U
    u_seed = np.random.randint(p, size = (n, n))
    for i in range(0, n):
        u_seed[i, i] = random.randint(1, p - 1) if u_seed[i, i] == 0 else u_seed[i, i]
    u = np.matrix(np.triu(u_seed))
    
    # Generating L
    l_seed = np.random.randint(p, size = (n, n))
    for i in range(0, n):
        l_seed[i, i] = random.randint(1, p - 1) if l_seed[i, i] == 0 else l_seed[i, i]
    l = np.matrix(np.tril(l_seed))
    
#     Creating K = U * L
    encryption_key = (l * u) % p
            
    # Creating K^{-1}
    bases = np.matlib.identity(n)
    
    y = []
    y.append(bases[:, 0] * XEuclidean().inverse_modulo(l[0, 0], p))
    for i in range(1, n):
        sum_ = 0
        for j in range(0, i):
            sum_ += (y[j] * l[i, j]) % p
        sum_ %= p
        y.append(np.array(((bases[:, i] - sum_) * XEuclidean().inverse_modulo(l[i, i], p)) % p))
    
    y = np.matrix(np.column_stack(y)).transpose()

    x = [0] * n
    x[n - 1] = y[n - 1, :] * XEuclidean().inverse_modulo(u[n - 1, n - 1], p)
    for i in range(n - 2, -1, -1):
        sum_ = 0
        for j in range(i + 1, n):
            sum_ += (x[j] * u[i, j]) % p
        sum_ %= p
        
        x[i] = np.array(((y[i, :] - sum_) * XEuclidean().inverse_modulo(u[i, i], p)) % p)
    
    decryption_key = np.matrix(np.reshape(x, (n, n)))

    return x, y, u, l, encryption_key, decryption_key

In [8]:
%%time

for i in range(0, 10):
    x, y, u, l, encryption_key, decryption_key = keygen(10, 2)

Wall time: 15.6 ms


In [9]:
sentence = np.random.randint(2, size = (1024,))

In [10]:
plain = ''.join(str(c) for c in sentence)
plain

'001010101011101011100111110100000001000010100010000000100001001000010000001101001110000110010110000111001111001000100101010110010000000110000010001000101110000011000001011011010001101010111110000111110001010111100101111111011111001001101001100111101000101101011010100110000100011001100110011001001110101100010000100000010111000101001100001010101111011110110011000000111111100010011011100000000001011101101011111001000010011110111001101110000111001001111111111111000001011011001001000110101011011011111010110010001100010111000011010001000011001000100111010010001101000011011001101011100000010111111001011001111111011001001010001000111111101100101001100100000101010010011000110001110011000110101101101101011110011101101001010111101000110011100110101110000011010010101100001100010101001111001010111010101110100111110011000011010101001001010110011011101010111101011001100111110011000010000110110100100001110010011010011111111110110110011100000000001001110110101110011110111110110100011000010011010000101

In [11]:
def chunks(message, n):
    return (message[0 + i:n + i] for i in range(0, len(message), n))

def to_calculatable(message, n):
#     numered_array = [int(i) for i in message]
#     numered_array = np.array([numered_array])
    
#     return numered_array.resize(n, 1)
    numered_array = np.array([[int(i) for i in message]], order = 'C')
    numered_array.resize(10, 1)
    return np.matrix(numered_array)

In [12]:
messages = []
for m in list(chunks(plain, 10)):
    print(m)
    messages.append(to_calculatable(m, 10))
    
messages

0010101010
1110101110
0111110100
0000010000
1010001000
0000100001
0010000100
0000110100
1110000110
0101100001
1100111100
1000100101
0101100100
0000011000
0010001000
1011100000
1100000101
1011010001
1010101111
1000011111
0001010111
1001011111
1101111100
1001101001
1001111010
0010110101
1010100110
0001000110
0110011001
1001001110
1011000100
0010000001
0111000101
0011000010
1010111101
1110110011
0000001111
1110001001
1011100000
0000010111
0110101111
1001000010
0111101110
0110111000
0111001001
1111111111
1100000101
1011001001
0001101010
1101101111
1010110010
0011000101
1100001101
0001000011
0010001001
1101001000
1101000011
0110011010
1110000001
0111111001
0110011111
1101100100
1010001000
1111111011
0010100110
0100000101
0100100110
0011000111
0011000110
1011011011
0101111001
1101101001
0101111010
0011001110
0110101110
0000110100
1010110000
1100010101
0011110010
1011101010
1110100111
1100110000
1101010100
1001010110
0110111010
1011110101
1001100111
1100110000
1000011011
0100100001
1100100110

[matrix([[0],
         [0],
         [1],
         [0],
         [1],
         [0],
         [1],
         [0],
         [1],
         [0]]),
 matrix([[1],
         [1],
         [1],
         [0],
         [1],
         [0],
         [1],
         [1],
         [1],
         [0]]),
 matrix([[0],
         [1],
         [1],
         [1],
         [1],
         [1],
         [0],
         [1],
         [0],
         [0]]),
 matrix([[0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [0],
         [0],
         [0],
         [0]]),
 matrix([[1],
         [0],
         [1],
         [0],
         [0],
         [0],
         [1],
         [0],
         [0],
         [0]]),
 matrix([[0],
         [0],
         [0],
         [0],
         [1],
         [0],
         [0],
         [0],
         [0],
         [1]]),
 matrix([[0],
         [0],
         [1],
         [0],
         [0],
         [0],
         [0],
         [1],
         [0],
         [0]]),
 matri

In [13]:
encrypted = []
for m in messages:
    encrypted.append((encryption_key * m) % 2)
    
encrypted

[matrix([[0],
         [1],
         [0],
         [0],
         [1],
         [1],
         [0],
         [1],
         [0],
         [1]], dtype=int32),
 matrix([[1],
         [1],
         [0],
         [1],
         [0],
         [1],
         [1],
         [1],
         [1],
         [0]], dtype=int32),
 matrix([[1],
         [0],
         [1],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1],
         [0]], dtype=int32),
 matrix([[1],
         [0],
         [1],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [0]], dtype=int32),
 matrix([[0],
         [0],
         [1],
         [0],
         [1],
         [0],
         [0],
         [0],
         [1],
         [0]], dtype=int32),
 matrix([[1],
         [0],
         [1],
         [1],
         [0],
         [0],
         [1],
         [1],
         [1],
         [0]], dtype=int32),
 matrix([[0],
         [0],
         [0],
         [1],
         [0],


In [24]:
decrypted = []
for c in encrypted:
    d = (decryption_key * c) % 2
    decrypted.append(np.reshape(np.asarray(d), (1, -1)))

decrypted[0][0][0]

0.0